[build]
  functions = "netlify-functions/functions"
  publish = "client/dist"

[functions]
  directory = "netlify-functions/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
